AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'test/acceptance/Vagrantfile'

Naming/FileName:
  Exclude:
    - 'vagrant-devcommands.gemspec'
    - 'test/acceptance/Vagrantfile'
    - 'test/integration/fixtures/**/Vagrantfile'
