AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Naming/FileName:
  Exclude:
    - 'test/integration/fixtures/**/Vagrantfile'
