AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: '3.0'

Layout/LineLength:
  Exclude:
    - 'test/acceptance/Vagrantfile'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Naming/FileName:
  Exclude:
    - 'test/acceptance/Vagrantfile'
    - 'test/integration/fixtures/**/Vagrantfile'
