language: ruby
sudo: false

jobs:
  include:
    - &test
      stage: test
      rvm: 2.3.7
      env: VER_VAGRANT=2.2.4 TRAVIS_COVERAGE=true
      script: bundle exec rake travis
    - <<: *test
      rvm: 2.3.7
      env: VER_VAGRANT=2.1.5
    - <<: *test
      rvm: 2.2.5
      env: VER_VAGRANT=2.0.4
    - <<: *test
      env: VER_VAGRANT=master
    - &test_acceptance
      stage: test (acceptance)
      rvm: 2.3.7
      env: VER_VAGRANT=2.2.4
      services: docker
      script: ./test/acceptance/test.sh
    - <<: *test_acceptance
      rvm: 2.3.7
      env: VER_VAGRANT=2.1.5
    - <<: *test_acceptance
      rvm: 2.2.5
      env: VER_VAGRANT=2.0.4
    - <<: *test_acceptance
      env: VER_VAGRANT=master
