language: ruby
sudo:     required

services: docker

jobs:
  include:
    - &test
      stage:  test
      rvm:    2.2.5
      env:    VER_VAGRANT=1.9.2 TRAVIS_COVERAGE=true
      script: bundle exec rake travis
    - <<: *test
      env:            VER_VAGRANT=1.8.7 VER_BUNDLER=1.12.5
      before_install: |-
        gem uninstall bundler -aIxq --force
        gem uninstall -Ixq --force -i /home/travis/.rvm/gems/ruby-2.2.5@global bundler
        gem install bundler -v "${VER_BUNDLER}"
    - <<: *test
      env: VER_VAGRANT=master
    - &test_acceptance
      stage:    test (acceptance)
      rvm:      2.2.5
      env:      VER_VAGRANT=1.9.2
      script:   ./test/acceptance/test.sh
    - <<: *test_acceptance
      env:            VER_VAGRANT=1.8.7 VER_BUNDLER=1.12.5
      before_install: |-
        gem uninstall bundler -aIxq --force
        gem uninstall -Ixq --force -i /home/travis/.rvm/gems/ruby-2.2.5@global bundler
        gem install bundler -v "${VER_BUNDLER}"
    - <<: *test_acceptance
      env: VER_VAGRANT=master
