ioctl_provision = "(grep -q 'mesg n' /root/.profile && sed -i '/mesg n/d' /root/.profile) || exit 0;"

Vagrant.configure('2') do |config|
  config.vm.define 'primary' do |primary|
    primary.vm.hostname  = 'primary.vagrant.devcommands'
    primary.ssh.username = 'root'

    primary.vm.provider 'docker' do |d|
      d.image   = 'nineseconds/docker-vagrant'
      d.has_ssh = true
    end

    primary.vm.provision :shell, privileged: false,
                                 inline:     ioctl_provision
  end

  config.vm.define 'secondary' do |secondary|
    secondary.vm.hostname  = 'secondary.vagrant.devcommands'
    secondary.ssh.username = 'root'

    secondary.vm.provider 'docker' do |d|
      d.image   = 'nineseconds/docker-vagrant'
      d.has_ssh = true
    end

    secondary.vm.provision :shell, privileged: false,
                                   inline:     ioctl_provision
  end
end
