name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - test
    tags:
      - '*'
  workflow_dispatch:

jobs:
  quality_actions:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - run: yamllint .
        working-directory: .github

  quality_ruby:
    runs-on: ubuntu-22.04

    env:
      VER_VAGRANT: 2.2.10

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
          bundler-cache: true

      - run: bundle exec rake style:ruby

  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '2.5'
            vagrant: 2.2.10
          - ruby: '2.6'
            vagrant: 2.2.19
          - ruby: '2.7'
            vagrant: 2.3.4
          - ruby: '3.0'
            vagrant: 2.3.7
          - ruby: '3.1'
            vagrant: 2.4.1
          - ruby: '3.2'
            vagrant: main

    env:
      VER_VAGRANT: ${{ matrix.vagrant }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake test:unit
      - run: bundle exec rake test:integration
