name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - test
    tags:
      - '*'
  workflow_dispatch:

jobs:
  quality_actions:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - run: yamllint .
        working-directory: .github

  quality_ruby:
    runs-on: ubuntu-24.04

    env:
      VER_VAGRANT: 2.3.5

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          rubygems: latest
          bundler-cache: true

      - run: bundle exec rake style:ruby

  test:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.0'
            vagrant: 2.3.5
          - ruby: '3.1'
            vagrant: 2.4.0
          - ruby: '3.2'
            vagrant: 2.4.3
          - ruby: '3.3'
            vagrant: main

    env:
      VER_VAGRANT: ${{ matrix.vagrant }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler-cache: true

      - run: bundle exec rake test:unit
      - run: bundle exec rake test:integration
