name: Code Quality

on: [push, pull_request]

jobs:
  quality_actions:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - run: yamllint .
        working-directory: .github

  quality_ruby:
    runs-on: ubuntu-22.04

    env:
      VER_VAGRANT: 2.2.10

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
          bundler-cache: true

      - run: bundle exec rake style:ruby
