name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        include:
          - ruby: '2.5'
            vagrant: 2.2.10
          - ruby: '2.6'
            vagrant: 2.2.19
          - ruby: '2.7'
            vagrant: 2.3.3
          - ruby: '3.0'
            vagrant: main
          - ruby: '3.1'
            vagrant: main

    runs-on: ubuntu-20.04

    env:
      VER_VAGRANT: ${{ matrix.vagrant }}

    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rake test:unit
    - run: bundle exec rake test:integration
