name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        include:
          - ruby: 2.4
            vagrant: 2.0.4
          - ruby: 2.5
            vagrant: 2.1.5
          - ruby: 2.6
            vagrant: 2.2.12
          - ruby: 2.7
            vagrant: master

    runs-on: ubuntu-20.04

    env:
      VER_VAGRANT: ${{ matrix.vagrant }}

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rake test:unit
    - run: bundle exec rake test:integration
